# Generated by Django 4.2.12 on 2026-02-27 11:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('login_user', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Логин')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('employee_number', models.CharField(max_length=20, unique=True, verbose_name='Табельный номер')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('organization', models.CharField(blank=True, max_length=100, verbose_name='Организация')),
            ],
        ),
        migrations.CreateModel(
            name='LicensePlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[А-ЯA-Z0-9]+$', 'Только буквы и цифры')], verbose_name='Государственный номер')),
            ],
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=50, verbose_name='Марка автомобиля')),
                ('pass_type', models.CharField(choices=[('permanent', 'Постоянный (сотрудник)'), ('temporary', 'Временный (гость)')], max_length=10, verbose_name='Тип пропуска')),
                ('start_date', models.DateField(verbose_name='Дата начала действия')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания (для временных)')),
                ('cargo_type', models.CharField(blank=True, max_length=100, verbose_name='Вид груза (для временных)')),
                ('entry_time', models.TimeField(blank=True, null=True, verbose_name='Время въезда (для временных)')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='access_control.employee')),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='access_control.guest')),
                ('license_plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access_control.licenseplate', verbose_name='ГНЗ')),
            ],
        ),
    ]
