# Generated by Django 4.2.12 on 2026-05-04 08:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessSubject',
            fields=[
                ('id', models.UUIDField(db_comment='ID', default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(db_comment='Дата создания', default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Субъект пропуска',
                'verbose_name_plural': 'Субъекты пропуска',
                'db_table': 'access_subjects',
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(db_comment='ID', default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(db_comment='Дата создания', default=django.utils.timezone.now, editable=False, verbose_name='Дата создания')),
                ('surname', models.CharField(db_comment='Фамилия', max_length=64, verbose_name='Фамилия')),
                ('first_name', models.CharField(db_comment='Имя', max_length=64, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, db_comment='Отчество', max_length=64, verbose_name='Отчество')),
                ('phone_number', models.CharField(blank=True, db_comment='Номер телефона', max_length=20, null=True, verbose_name='Номер телефона')),
                ('login_user', models.CharField(db_comment='Логин', db_index=True, max_length=64, unique=True, verbose_name='Логин')),
                ('employee_number', models.CharField(db_comment='Табельный номер', max_length=20, unique=True, verbose_name='Табельный номер')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'employees',
                'ordering': ['surname', 'creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.UUIDField(db_comment='ID', default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(db_comment='Дата создания', default=django.utils.timezone.now, editable=False, verbose_name='Дата создания')),
                ('surname', models.CharField(db_comment='Фамилия', max_length=64, verbose_name='Фамилия')),
                ('first_name', models.CharField(db_comment='Имя', max_length=64, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, db_comment='Отчество', max_length=64, verbose_name='Отчество')),
                ('phone_number', models.CharField(blank=True, db_comment='Номер телефона', max_length=20, null=True, verbose_name='Номер телефона')),
                ('organization', models.CharField(blank=True, max_length=100, verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Гость',
                'verbose_name_plural': 'Гости',
                'db_table': 'guests',
                'ordering': ['surname', 'creation_date'],
            },
        ),
        migrations.CreateModel(
            name='LicensePlate',
            fields=[
                ('id', models.UUIDField(db_comment='ID', default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(db_comment='Дата создания', default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('plate_number', models.CharField(db_comment='Государственный номер', db_index=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[А-ЯA-Z0-9]+$', 'Только буквы и цифры')], verbose_name='Государственный номер')),
            ],
            options={
                'verbose_name': 'Регистрационный номер',
                'verbose_name_plural': 'Регистрационные номера',
                'db_table': 'license_plates',
                'ordering': ['plate_number'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(db_comment='ID', default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(db_comment='Дата создания', default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('brand', models.CharField(blank=True, db_comment='Марка транспортного средства', max_length=32, null=True, verbose_name='Марка транспортного средства')),
                ('model', models.CharField(blank=True, db_comment='Модель транспортного средства', max_length=32, null=True, verbose_name='Модель транспортного средства')),
                ('color', models.CharField(blank=True, db_comment='Цвет транспортного средства', max_length=16, null=True, verbose_name='Цвет транспортного средства')),
                ('license_plate', models.ForeignKey(blank=True, db_comment='Гос.номер', null=True, on_delete=django.db.models.deletion.PROTECT, to='access_control.licenseplate', verbose_name='Гос.номер')),
            ],
            options={
                'verbose_name': 'Транспортное средство',
                'verbose_name_plural': 'Транспортное средство',
                'db_table': 'vehicles',
                'ordering': ['brand', 'model', 'creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.UUIDField(db_comment='ID', default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(db_comment='Дата создания', default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('pass_type', models.CharField(choices=[('Постоянный', 'Permanent'), ('Временный', 'Temporary')], db_comment='Тип пропуска', max_length=10, verbose_name='Тип пропуска')),
                ('start_date', models.DateField(verbose_name='Дата начала действия')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания (для временных)')),
                ('cargo_type', models.CharField(blank=True, max_length=100, verbose_name='Вид груза (для временных)')),
                ('entry_time', models.TimeField(blank=True, null=True, verbose_name='Время въезда (для временных)')),
                ('subject', models.ForeignKey(db_comment='Субъект пропуска', on_delete=django.db.models.deletion.CASCADE, to='access_control.accesssubject', verbose_name='Субъект пропуска')),
            ],
            options={
                'verbose_name': 'Пропуск',
                'verbose_name_plural': 'Пропуска',
                'db_table': 'passes',
                'ordering': ['creation_date'],
            },
        ),
        migrations.AddField(
            model_name='accesssubject',
            name='employee',
            field=models.ForeignKey(blank=True, db_comment='Сотрудник', null=True, on_delete=django.db.models.deletion.PROTECT, to='access_control.employee', verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='accesssubject',
            name='guest',
            field=models.ForeignKey(blank=True, db_comment='Гость', null=True, on_delete=django.db.models.deletion.PROTECT, to='access_control.guest', verbose_name='Гость'),
        ),
        migrations.AddField(
            model_name='accesssubject',
            name='vehicle',
            field=models.ForeignKey(db_comment='Транспортное средство', on_delete=django.db.models.deletion.PROTECT, to='access_control.vehicle', verbose_name='Транспортное средство'),
        ),
        migrations.AddConstraint(
            model_name='accesssubject',
            constraint=models.UniqueConstraint(fields=('employee', 'guest'), name='unique_access_subjects_employee_guest'),
        ),
        migrations.AddConstraint(
            model_name='accesssubject',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('employee__isnull', True), ('guest__isnull', False)), models.Q(('employee__isnull', False), ('guest__isnull', True)), _connector='OR'), name='unique_access_one_subject'),
        ),
    ]
