# Generated by Django 4.2.12 on 2026-05-22 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassLogsModel',
            fields=[
                ('id', models.UUIDField(db_comment='ID', default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(db_comment='Дата создания', default=django.utils.timezone.now, editable=False, verbose_name='Дата создания')),
                ('message', models.CharField(blank=True, db_comment='Сообщение', max_length=2048, null=True, verbose_name='Сообщение')),
                ('pass_object', models.ForeignKey(blank=True, db_comment='Пропуск', null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_control.pass', verbose_name='Пропуск')),
                ('user', models.ForeignKey(blank=True, db_comment='Пользователь', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
                'db_table': 'pass_logs',
                'ordering': ['-creation_date'],
            },
        ),
    ]
