# Generated by Django 4.2.12 on 2026-05-21 21:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['brand', 'model', 'creation_date'], 'verbose_name': 'Транспортное средство', 'verbose_name_plural': 'Транспортные средства'},
        ),
    ]
