# Generated by Django 4.2.12 on 2026-05-22 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('access_control', '0002_passlogsmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passlogsmodel',
            name='pass_object',
        ),
        migrations.AddField(
            model_name='passlogsmodel',
            name='content_type',
            field=models.ForeignKey(blank=True, db_comment='Объект модели', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Объект модели'),
        ),
        migrations.AddField(
            model_name='passlogsmodel',
            name='key',
            field=models.UUIDField(blank=True, db_comment='Ключ записи', null=True, verbose_name='Ключ записи'),
        ),
        migrations.AddField(
            model_name='passlogsmodel',
            name='topic_id',
            field=models.UUIDField(blank=True, db_comment='ID общего топика логов', null=True, verbose_name='ID общего топика логов'),
        ),
    ]
