# Generated by Django 4.2.12 on 2026-05-22 14:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0003_remove_passlogsmodel_pass_object_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pass',
            new_name='PassModel',
        ),
        migrations.CreateModel(
            name='LicensePlateForManualHandle',
            fields=[
                ('id', models.UUIDField(db_comment='ID', default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(db_comment='Дата создания', default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('license_plate', models.OneToOneField(db_comment='Гос. номер', on_delete=django.db.models.deletion.CASCADE, to='access_control.licenseplate', verbose_name='Гос. номер')),
            ],
            options={
                'verbose_name': 'Регистрационный номер для ручной обработки',
                'verbose_name_plural': 'Регистрационные номера для ручной обработки',
                'db_table': 'license_plates_for_manual_handle',
                'ordering': ['-creation_date'],
            },
        ),
    ]
